'use client'

import React, {Fragment, useEffect, useState} from 'react';
import {Provider} from 'react-redux';
import Header from '@/shared/components/Header';
import store from '@/shared/redux/store';

// export const metadata: Metadata = {
//   title: 'Dashboard Sales',
//   description: 'Generated by create next app',
// };

export default function DashboardLayout({
                                            children,
                                        }: Readonly<{
    children: React.ReactNode;
}>) {


    const [lateLoad, setlateLoad] = useState(false);
    const Add = () => {
        document.querySelector("body")?.classList.remove("error-1");
        document.querySelector("body")?.classList.remove("landing-body");
    };

    useEffect(() => {
        Add();
        setlateLoad(true);
    });

    let [MyclassName , setMyClass] = useState("");

    const Bodyclickk = () => {
        if (localStorage.getItem("Syntoverticalstyles") == "icontext") {
            setMyClass("");
        }
    };
    useEffect(() => {
        // @ts-ignore
        import('preline');

    }, []);

    return (
        <html lang="en">
        <body>
        <Fragment>
            <Provider store={store}>
                <div style={{display: `${lateLoad ? 'block' : 'none'}`}}>
                    <Header/>
                    <div className="page">
                        <main>{children}</main>
                    </div>
                </div>
            </Provider>
        </Fragment>
        </body>
        </html>
);
}
