import React from "react";
import type {Metadata} from "next";
import {Sidebar} from "@/shared/components/Sidebar";
import {Header} from "@/shared/components/Header";

export const metadata: Metadata = {
    title: "Dashboard Sales",
    description: "Generated by create next app",
};

export default function DashboardLayout({
                                            children,
                                        }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body>
        <div className="page">
            <Header/>
            <Sidebar/>
            <main>
                {children}
            </main>
        </div>
        </body>
        </html>
    );
}
